spring.application.name=Course Management System
# SQL Server ba\u011flant\u0131 ayarlar\u0131
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=UniversityCourseSelection
spring.datasource.username="sa"
spring.datasource.password="1234"
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA ve Hibernate ayarlar\u0131
spring.jpa.hibernate.ddl-auto=update  # Veritaban\u0131 \u015femas\u0131 otomatik olarak g\u00fcncellenir
spring.jpa.show-sql=true  # SQL sorgular\u0131n\u0131 konsolda g\u00f6sterir
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.application.name=Course Management System
